site:
  name: QYep
  site: 'https://www.qingtaors.top'

# Default SEO metadata
metadata:
  title:
    default: QYep
    template: '%s â€” QYep'
  description: "My devlog: project progress, problems, and solutions."

googleSiteVerificationId: null


i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    post:
      permalink: '/blog/%slug%'
    list:
      pathname: 'blog'
tag:
  robots:
    index: false




ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"


analytics:
  vendors:
    googleAnalytics:
      id: "G-QQ7RLT57HJ"
